### ISSUE TITLE
Always disabled (2018 MBP, 10.13.6)

### ISSUE THREAD

**Issue by JayBrown** [niw/HapticKey#25]
The new version 0.4.6 remains disabled in 10.13.6 on a 2018 MBP. Clicking on "ESC…" and "All Taps" doesn't enable. Tried deleting preferences; no change. Note: also have BetterTouchTool installed; maybe that's interfering? (But it didn't with the previous version.)

**Comment by niw** [comment]
Hi @JayBrown.
If it was working but not working now, probably because of known issue #22, which you may need to toggle accessibility permission for HapticKey after updating it.
HapticKey should not be interfering with the other apps, but it depends on the such applications’ implementation.
If you can’t solve the issue after toggling accessibility permission, I may want to ask you to get an application log to see what’s going on in the Console.app.

**Comment by JayBrown** [comment]
You're right. Thank you. Should've scanned it before launching. Then I would've known that it isn't codesigned. ;)

**Comment by niw** [comment]
@JayBrown Sorry for the inconvenience...!
