### ISSUE TITLE
"Start on login" is not shown as enabled but it is (and cannot disable)

### ISSUE THREAD

**Issue by lpla** [niw/HapticKey#29]
After some months using this app, I wanted to disable starting on login but looks like it is disabled even if I click on it several times (but it is enabled if I restart):

<img width="372" alt="Captura de pantalla 2019-03-09 a las 0 42 33" src="https://user-images.githubusercontent.com/1533393/54062068-436c8a80-4204-11e9-94d0-fe9a10e73483.png">

If this bug isn't easily fixable in HapticKey code, how can I disable that manually?

Thanks

**Comment by niw** [comment]
Sorry for not replying this for a while. Let me take a look soon.

**Comment by niw** [comment]
@lpla Do you see HapticKey in System Preferences... → Users & Groups → Current User → Login Items?
This "Start on Login" is checking this item and add, remove Haptic Key to run the application when user is logging in.

<img width="519" alt="Login Items" src="https://user-images.githubusercontent.com/13096/58357125-7a7b3100-7e2e-11e9-9bd3-4e8215c544f4.png">

**Comment by lpla** [comment]
Oh! Yes! I didn't know about this menu. Looks like I had duplicated entries from older versions or app located at other folders, and after deleting all entries now it is working!

If I get this issue again I will check this menu to report this issue more carefully. Meanwhile, I will close the issue as I can't reproduce it now after deleting all entries from this System Preferences menu.

Thanks!

**Comment by niw** [comment]
I see, thank you for reporting! (and again, sorry for not replying for a while.)

This start up item feature is [using deprecated API](https://github.com/niw/HapticKey/blob/master/HapticKey/Classes/HTKLoginItem.m#L16) due to new API’s behavior and it’s based on the application main bundle path, so it should work even if the system has multiple copy of it.

However, I didn’t test that case yet. So, let me try to reproduce and if it’s the case, I will fix it.
