### ISSUE TITLE
HapticKey blocks Notification Centre Gesture (two fingers) on the Trackpad MB2019 16"

### ISSUE THREAD

**Issue by hackToxa** [niw/HapticKey#36]
Hi,

I really like HapticKey.
Unfortunately, on my new MB 2019 16", I noticed it is blocking the Notification Gesture.

Only per google search, I found a relation and after switching HapticKey of, it works again.
Seems to be a bug.

BR

**Comment by niw** [comment]
Hi, @hackToxa, thank you for reporting.

I tested on my MacBook Pro (2017) and the notification center gesture, two finger swiping from right outside of track pad to inside of track pad works while HapticKey.app is running and enabled, however, I observed the gesture stops working after quitting HapticKey.app or some similar operation with the application launching or quitting.

Are you seeing similar behavior on your environment as well?

I will investigate it closely this behavior later.

**Comment by Vxider** [comment]
@niw I  have a 16 inch MBP(2019), same with you, notification center gesture works well when using HapicKey, but stop working after quitting. I encountered this problem before using HapicKey(notification center and zoom in/out gesture). I even write a applescript to reset the touchpad options in System Preferences.

**Comment by etienneleblan** [comment]
16inch MBP here too, not having any issues so far

**Comment by niw** [comment]
Currently I found possible race condition of how HapticKey is handling gesture events and how application quits since most of case HapticKey quits by menu item “Quite HapticKey” however, selecting that menu item is actually gesture and seems like that causes some timing problem and messed `CGEventTap`, which HapticKey is using to detect taps on Touch Bar.

Current workaround is quitting HapticKey (if neeeded,) use ⌘Q short-cut key while menu is open, or use Activity Monitor to quit it.
Another workaround is not using “All Taps on Touch Bar” but use “ESC and F1, F2, etc. Keys”.
I understand that's not enough in some specific usage case, that might be enough. 

At this moment, I do not have a solution yet. However, I keep investigate the possible solution for this.

**Comment by niw** [comment]
I think d2aec16 may fix this issue. Testing now.

**Comment by niw** [comment]
Hi, @hackToxa, @Vxider  and @etienneleblan!

I made a binary from the latest branch for testing before releasing.
[HapticKey.app-20200322210145.zip](https://github.com/niw/HapticKey/files/4366352/HapticKey.app-20200322210145.zip)

This should fix the issue mentioned here, also hopefully it is handling the taps in better way.
If you have a time, please test it and let me know if you find any problems.

Thank you!

**Comment by Vxider** [comment]
Thanks for your work, 20200322210145 works well for my 16 inch MBP(2019).

**Comment by niw** [comment]
@Vxider Thank you for testing!

**Comment by niw** [comment]
Released 0.5.0.
https://github.com/niw/HapticKey/releases/tag/0.5.0

Thank you for your help!
