### ISSUE TITLE
Special configuration for Terminal?

### ISSUE THREAD

**Issue by jhfrontz** [niw/HapticKey#38]
I've got HapticKey running, configured, and enabled. It successfully vibrates the trackpad when I touch the `esc` on the trackpad when using, for example, Safari or the Finder.

However, I don't get any sort of response when I hit `esc` while using Terminal.

Is there something I need to configure to enable use with certain applications?

**Comment by jhfrontz** [comment]
Aha (again!)-- `Secure Keyboard Entry` must be **dis**abled in Terminal. I guess this makes sense since the Touch Bar is on the input stream and presumably HapticKey is intercepting "keypresses".

**Comment by niw** [comment]
Ah, I see. If the application doesn’t support `CGEventTap`, it doesn’t work and it’s limitation of this application.

**Comment by jhfrontz** [comment]
> Ah, I see. If the application doesn’t support `CGEventTap`, it doesn’t work and it’s limitation of this application.

Right -- I had forgotten that I had enabled `Secure Keyboard Entry` years ago;

**Comment by niw** [comment]
There might be many applications that support such secure keyboard entry.

[This documentation](https://developer.apple.com/library/archive/technotes/tn2150/_index.html) describes the API used for that functionality and clearly `CGEventTap` for the keyboard events is the one included to be prevented by this API.

If you use “All Taps on Touch Bar” instead of “ESC and F1, F2, etc. Keys,” however, it uses different type of events, thus even on such application, HapticKey can trigger the feedback.

**Comment by jhfrontz** [comment]
> If you use “All Taps on Touch Bar” instead of “ESC and F1, F2, etc. Keys,” however, it uses different type of events, thus even on such application, HapticKey can trigger the feedback.

Thanks, that is really good advice -- and it does allow for `Secure Keyboard Entry` in Terminal.
