### ISSUE TITLE
Can it cause damage to Haptic Engine?

### ISSUE THREAD

**Issue by StealthWire** [niw/HapticKey#39]
First things first, superb app. Feels like this is the way Mac should be shipped by default. However, it makes me question why did apple engineers decide against it? Is it due to the concerns of overuse of haptic engine?

Can HapticKey cause any long term damage to the haptic engine? The utilisation of Haptic Engine is doubled than the intended design. Ik sounds silly and dumb but it might be a concern to many people. Once again thank you for the great application.

**Comment by niw** [comment]
@StealthWire Interesting question... and I have no answer for your question of using it more than expected causes long-term problem on track pad Haptic Engine or not, because obviously, I am not hardware engineer at Apple.

However, I can mention one thing that current HapticKey implementation is using Apple’s designed haptic feedback wave patterns, which is actually one of reasons of other issue reported #24.
Therefore, in terms of this question, I believe using HapticKey may not impact to the haptic engine itself for because of its usage.

Also in fact, Apple publicly allow each app developers to [use Haptic Engine as a part of each app behavior](https://developer.apple.com/documentation/appkit/nshapticfeedbackperformer).
For example, there could be a valid app that as Apple expected uses Haptic Engine for reacting users input such as triggering it when fitting an object to the guide on the screen.
Therefore, the total amount of usage of Haptic Engine is depending on how users are using each app and so Haptic Key and other such applications can be considered as a same category and technically we can say it could be a part of Apple’s software and hardware design considerations.

As summary, I personally don’t think HapticKey can damage Haptic Engine, however, please understand that I can’t guarantee anythings.

**Comment by StealthWire** [comment]
Ahh the 2nd last para makes total sense. I did not take that into account, so it seems apple has indeed taken into account the number of times haptic engine might be triggered by other app. Nice to know, I can continue punching the touch bar, thanks to you for make it more productive. And yes I understand, being an open source app you have no liability to guarantee. 

🤓 thank you for your time and effort.
