### ISSUE TITLE
Haptic Key macOS 11.1 compatibility

### ISSUE THREAD

**Issue by pedserdoc** [niw/HapticKey#45]
I have attempted to install Haptic Key v0.5 on macOS 11.1 without success. I am greeted by a dialog box that states the developer must update the app for installation to proceed. Is there a workaround for Big Sur compatibility or must we await a new version?

**Comment by niw** [comment]
For testing #42, there is a prebuild binary from the latest source code [HapticKey.app-cd221bc.zip](https://github.com/niw/HapticKey/files/5753630/HapticKey.app-cd221bc.zip) so you can try this instead.

However, probably the dialog you see is the security dialog that macOS os presenting for the binary which code is not signed. Since I am a personal developer and not yet have a plan to prepare for the code signing for prebuilt binaries I distributed here, you need to allow HapticKey to execute from the Security & Privacy settings in Preferences as described in [README.md](https://github.com/niw/HapticKey/blob/master/README.md).

Could you try these options to see if it works?
If it still doesn’t work, if you don’t mind, please provide which MacBook you’re using also a screenshot if error message would help.

**Comment by pedserdoc** [comment]
My Mac is a 2019 MacBookPro. The dialog box states "Haptic Key cannot be installed because macOS cannot check the app for malicious software", which likely means it's not signed. However, installation with the new universal binary version of v0.5 cd221bc was successful by use of the command button and giving Haptic Key Accessibility privileges within the Privacy and Security control panel. Thank you for your prompt response!

**Comment by niw** [comment]
@pedserdoc Sounds good!! Thank you for testing it! If you found any problems, please feel free to open a new issue.
