### ISSUE TITLE
Not Installing M1 Macbook Pro

### ISSUE THREAD

**Issue by iKarans** [niw/HapticKey#54]
“HapticKey” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

I get this pop up when I open the app after I downloaded the latest version.

**Comment by gashead76** [comment]
> “HapticKey” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.
> 
> I get this pop up when I open the app after I downloaded the latest version.

You can right click (or Control-Click) on the application icon to open it after a couple warning dialogs. If you happen to be on Monterey beta, it does not seem to be working at all.

**Comment by niw** [comment]
This is because the pre-build binary I am distributing from GitHub releases page are not signed nor notarized for now.
As @gashead76 mentioned, you need to accept the warning dialog by opening app by click icon with Ctrl to Open. This is also described in README so please refer it as well.

If you're concerned about binary itself, you can always build your own binary from the source code (sorry, I understand it's not easy, but the best safety...) or probably you can remove `com.apple.quarantine` attribute from downloaded zip file to disable Gate Keeper check.
```
$ xattr -d com.apple.quarantine HapticKey.app.zip
```

I am considering to sign and notarize pre-build binary distributions... yet it is not completed. 
This is also related to #22.

**Comment by iKarans** [comment]
Thank you! Loving the app already.
