### ISSUE TITLE
Add Homebrew Cask support

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [niw/HapticKey#8]
As the title, I hope HapticKey can be installed through Homebrew.

**Comment by chrisballinger** [comment]
@CaptainYukinoshitaHachiman Here's a guide if you'd like to make one and submit a PR. They won't merge non-stable releases but it can be installed thru a tap https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by niw** [comment]
Currently I’m not signing any pre build binaries and yet have no plan to do so.

I understand that current distribution that is using Github release page isn’t ideal solution.
In future at some point, I prefer to support [Sperkle](https://sparkle-project.org/) and probably also Homebrew Cask.

**Comment by claui** [comment]
This issue can be closed because [Homebrew Cask support was added](https://github.com/Homebrew/homebrew-cask/pull/49979) last week.

Note that [apps which have only pre-release versions](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version) are **always welcome** to Homebrew Cask. [Unsigned binaries](https://github.com/niw/HapticKey/issues/8#issuecomment-361160046) are fine, too. That risk is up to the user, and we want to leave the decision to them.

**Comment by niw** [comment]
@claui Oh, nice! Thank you! I’m going to close this issue.
